CIA/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CIA.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Home()
        {
            return View();
        }
    }
}

CIA/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CIA_MAL.Model;
using CIA_BLL.IRepository;
using CIA_BLL.Repository;
using CIA_BLL.CommonClass;
using CIA_BLL.ErrorHandling;
using System.Drawing;
using System.Text;
using System.IO;

namespace CIA.Controllers
{
    public class SecurityController : Controller
    {
        ISecurityValdiate Login_valid = new SecurityValdiate();
        // GET: Security
        public ActionResult Login()
        {
            Session["CAPTCHA"] = GetRandomText();
            ViewBag.randomCaptcha = Session["CAPTCHA"].ToString();
            return View();
        }

        public JsonResult Loginchecks(string username, string password,string c_Captcha)
        {
            ResultStatus rs = new ResultStatus();
            try
            {
                Session["user_ad"] = username.ToString();

                string clientCaptcha = c_Captcha;
                string serverCaptcha = Session["CAPTCHA"].ToString();

                if (!clientCaptcha.Equals(serverCaptcha))
                {
                   // ViewBag.CaptchaError = "Sorry, please write exact text as written above.";
                    rs.Status = "Failure";
                    rs.MSG = "Sorry, Invalid Captcha! Write exact text as given.";
                    //return View();
                }
                else
                {
                    // continue with login validation
                    rs = Login_valid.Loginchecks(username, password);
                    if (rs.Status == "Success")
                    {
                        SessionObj.LoginName = username;
                        var res = (LoginDetail)rs.obj;
                        SessionObj.UserMst_ID = Convert.ToString(res.UserMst_ID);
                        SessionObj.LoginName = res.LoginName;
                        SessionObj.UsrName = res.UsrName;
                        SessionObj.Passwrd = res.Passwrd;
                        SessionObj.UsrRole = res.UsrRole;
                        SessionObj.is_Active = res.is_Active;
                        rs.Role = res.UsrRole;
                    }
                    else
                    {
                        rs.Status = "Failure";
                        //rs.MSG = "You are not authorized to ‘Sign in’";
                    }
                }
                
            }
            catch (Exception ex)
            {
                rs.Status = "Failure";
                if (ex.Message != null || ex.Message != "")
                {
                    rs.MSG = ex.Message;
                }
                else
                {
                    rs.MSG = ex.StackTrace;
                }
                ExceptionLogging.LogException(ex);
            }
            return Json(rs, JsonRequestBehavior.AllowGet);
        }

        private string GetRandomText()
        {
            StringBuilder randomText = new StringBuilder();
            string alphabets = "012345679ACEFGHKLMNPRSWXZabcdefghijkhlmnopqrstuvwxyz";
            Random r = new Random();
            for (int j = 0; j <= 5; j++)
            {
                randomText.Append(alphabets[r.Next(alphabets.Length)]);
            }
            return randomText.ToString();
        }
        
        public FileResult GetCaptchaImage()
        {
            string text = Session["CAPTCHA"].ToString();

            //first, create a dummy bitmap just to get a graphics object
            Image img = new Bitmap(1, 1);
            Graphics drawing = Graphics.FromImage(img);

            Font font = new Font("Arial", 15);
            //measure the string to see how big the image needs to be
            SizeF textSize = drawing.MeasureString(text, font);

            //free up the dummy image and old graphics object
            img.Dispose();
            drawing.Dispose();

            //create a new image of the right size
            img = new Bitmap((int)textSize.Width + 40, (int)textSize.Height + 20);
            drawing = Graphics.FromImage(img);

            Color backColor = Color.SeaShell;
            Color textColor = Color.Red;
            //paint the background
            drawing.Clear(backColor);

            //create a brush for the text
            Brush textBrush = new SolidBrush(textColor);

            drawing.DrawString(text, font, textBrush, 20, 10);

            drawing.Save();

            font.Dispose();
            textBrush.Dispose();
            drawing.Dispose();

            MemoryStream ms = new MemoryStream();
            img.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
            img.Dispose();

            return File(ms.ToArray(), "image/png");
        }

        public ActionResult Logout()
        {
            if (Session["user_ad"] != null)
            {
                Login_valid.LogOutInser(Convert.ToString(Session["user_ad"]));
                Session["Display_name"] = null;
                Session["user_ad"] = null;
                Session["manager_ad_id"] = null;
                Session["is_hr"] = null;
                Session["is_pm"] = null;

                Session.Clear();
                Session.Abandon();
            }
            return View("Login");
        }

        public JsonResult BrowserTabTExit()
        {
            var a = HttpContext.Request.Cookies["RefreshFilter"];
            long result = 0;

            if (Session["user_ad"] != null)
            {
                //if (Session["clickedFrm"] == null)
                //{                            
                Login_valid.LogOutInser(Convert.ToString(Session["user_ad"]));
                Session["Display_name"] = null;
                Session["user_ad"] = null;
                Session["manager_ad_id"] = null;
                Session["is_hr"] = null;
                Session["is_pm"] = null;

                Session.Clear();
                Session.Abandon();
                //}
            }
            return Json(result);

        }
    }
}

CIA/Views/Security/BrowserCheck.cshtml
@{
    ViewBag.Title = "BrowserCheck";
    Layout = "~/Views/Shared/_CommonLayout.cshtml";
}

<center>
    <br /><br />
    <div style="width: 40%; margin-top: 9.75%">
        <div class="Bpan grad">
            <div id="Content1" class="Bpan-body" style="line-height: 11px; margin-top: 17px;">
                <table>
                    <tr><td style="font-size:45px">&nbsp;</td></tr>
                    <tr>
                        <td align="center" style="text-align: center; font-family: 'Segoe UI'; padding-bottom: 20px; ">
                            <i style="font-size: 58px" class="fa fa-warning"></i>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" style="text-align: center; font-family: 'Segoe UI'; padding-bottom: 20px; font-size: 12pt; ">
                            <span style="margin-top: 10px; font-family: 'Segoe UI'; font-size: 12pt; color:red;">Please use chrome browser for better user experience.</span>
                        </td>
                    </tr>
                    @*<tr>
                            <td style="text-align: center; font-family: 'Segoe UI'; font-size: 12pt; ">
                                <a id="def" href='@Url.Action("LoginView", "Security")'> Click here to Login again</a>
                            </td>
                        </tr>*@
                </table>
            </div>
        </div>

    </div>
</center>


<style>
    #tbldata_wrapper {
        background: #F1F1F1;
    }

    #tbldata_processing {
        display: none;
    }

    .Bpan {
        font-size: 12pt;
        margin-bottom: 8px;
        font-family: 'Segoe UI';
        min-height: 200px;
        background-color: #ffffff;
        border: 1px solid transparent;
        border-color: #C5C5C5;
        border-radius: 0px;
        -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
        box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
    }

    .Bpan-heading {
        font-size: 12pt;
        padding: 7px 5px;
        font-family: 'Segoe UI';
        border-bottom: 1px solid transparent;
        color: #333333;
        background-color: #E1E1E1;
        border-color: #D4D4D4;
    }

    .Bpan-body {
        padding: 5px;
        font-size: 12pt;
        font-family: 'Segoe UI';
    }

    .btnSelect {
        background-color: #333;
        color: #DDDDDD;
        text-decoration: none;
    }

    .grad {
        background: red; /* For browsers that do not support gradients */
        background: -webkit-linear-gradient(left top, #ffffff, #ffffff); /* For Safari 5.1 to 6.0 */
        background: -o-linear-gradient(bottom right, #ffffff, #ffffff); /* For Opera 11.1 to 12.0 */
        background: -moz-linear-gradient(bottom right, #ffffff, #ffffff); /* For Firefox 3.6 to 15 */
        background: linear-gradient(to bottom right, #ffffff, #ffffff); /* Standard syntax */
    }
</style>

CIA/Views/Security/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}


<link href="~/Styles/UserStyles/Login.css" rel="stylesheet" />
<script src="~/Scripts/User_Defined/login.js"></script>

<link href="~/Styles/UserStyles/button_style.css" rel="stylesheet" />

<style>
    #btnsubmit {
    }

        #btnsubmit span {
            cursor: pointer;
            display: inline-block;
            position: relative;
            transition: 0.5s;
        }

            #btnsubmit span:after {
                content: '';
                position: absolute;
                opacity: 0;
                top: 0;
                right: -10px;
                transition: 0.5s;
            }

        #btnsubmit:hover span {
            padding-right: 25px;
        }

            #btnsubmit:hover span:after {
                opacity: 10;
                right: 0;
            }
</style>

<style>
    .button {
        color: #fff;
        background-color: rgb(89,89,89);
        border-color: rgb(89,89,89);
        font-family: 'Segoe UI';
        border-radius: 0px;
        display: inline-block;
        /*padding: 6px 12px;*/
        padding: 0px;
        font-size: 12pt;
        height: 32px;
        width: 65px;
        margin-bottom: 0;
        /*font-size: 14px;*/
        font-weight: normal;
        line-height: 1.42857143;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        -ms-touch-action: manipulation;
        touch-action: manipulation;
        cursor: pointer;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        background-image: none;
        border: 1px solid transparent;
        border-radius: 0px;
    }

    .button5 {
        background-color: white;
        color: black;
        border: 2px solid #555555;
    }

        .button5:hover {
            background-color: #4681f4;
            color: white;
        }

    .input-container {
        display: -ms-flexbox; /* IE10 */
        display: flex;
        width: 100%;
    }

    .icon {
        padding: 7px;
        background: #B0C4DE;
        color: black;
        margin-left: -8px;
        text-align: center;
    }
</style>
<div ng-app="lgapp" ng-controller="lgctrl">
    <div class="row" style="margin-top: 155px; border-radius: 0px; margin-right: 0px;">

        <div class="col-md-9">
            &nbsp;
        </div>
        <div class="col-md-3" style="padding: 0px; ">
            <div class="panel panel-default" style="border-radius: 0px; margin-top:0px; margin-right: 60px;">
                <div class="panel-body" style="background-color: #f5f5f5; border-radius: 0px;">
                    <div class="row">
                        <div class="col-md-12" style="margin-top:0px; margin-bottom:0px;">
                            <div class="form-group" style="border-radius:0px;">
                                <input type="text" ng-model="Username" autofocus placeholder="Username" class="form-control" autocomplete="off" style="border-radius: 0px; z-index: 0; font-size: 12pt; font-family: 'Segoe UI';" />
                                <i id="ic_user" class="fa fa-user" aria-hidden="true"> &nbsp</i>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="margin-top:15px;">
                        <div class="col-md-12" style="margin-top:0px; margin-bottom:0px;">
                            <div class="form-group" style="border-radius:0px;">
                                <input id="passwrd" type="password" ng-model="Password" ng-enter="SigninAction()" placeholder="Password" class="form-control" autocomplete="off" style="border-radius: 0px; z-index: 0; font-size: 12pt; font-family: 'Segoe UI';" />
                                <i class="fa fa-key"> &nbsp</i>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="margin-top:15px;">
                        <div class="col-md-12" style="margin-top: 0px; margin-bottom: 0px; border: 0px outset; background: lightgoldenrodyellow;">
                            <p style="font-weight:bold;color:red;">@ViewBag.randomCaptcha</p>
                            <input type="text" ng-model="clientCaptcha" placeholder="Enter Captach as above text exactly" class="form-control" autocomplete="off" style="border-radius: 0px; z-index: 0; font-size: 10pt; font-family: 'Segoe UI';" />
                            @*<p style="font-weight:bold;color:red;">@ViewBag.CaptchaError</p>*@
                        </div>
                    </div>
                    <div class="row" style="margin-top:15px; margin-bottom:0px;">
                        <div class="col-md-6" style="margin-top:0px; margin-bottom:0px;">
                            <button id="btnsubmit" ng-click="SigninAction('signin')" type="button" class="button button5" style="width:100%;"><span>Sign in</span></button>
                        </div>
                        <div class="col-md-6" style="margin-top:0px; margin-bottom:0px;">
                            <button id="btnsubmit" ng-click="SigninAction('reset')" type="button" class="button button5" style="width:100%;"><span>Reset</span></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!------------------------------------------------gets value from script---------------------->
@Html.Hidden("lgurl", Url.Action("Loginchecks", "Security"))
@Html.Hidden("Hmurl", Url.Action("Home", "Dashboard"))


<script language="JavaScript">
// Browserdetectionscript made by Henrik Petersen / NetKontoret
// Script explained at www.echoecho.com/javascript.htm
// Please do not remove this and the two lines above.
// Detect the browsername
var nVer = navigator.appVersion;
var nAgt = navigator.userAgent;
var browserName  = navigator.appName;
var fullVersion  = ''+parseFloat(navigator.appVersion);
var majorVersion = parseInt(navigator.appVersion,10);
var nameOffset,verOffset,ix;

// In Opera 15+, the true version is after "OPR/"
if ((verOffset=nAgt.indexOf("OPR/"))!=-1) {
 browserName = "Opera";
 fullVersion = nAgt.substring(verOffset+4);
}
// In older Opera, the true version is after "Opera" or after "Version"
else if ((verOffset=nAgt.indexOf("Opera"))!=-1) {
 browserName = "Opera";
 fullVersion = nAgt.substring(verOffset+6);
 if ((verOffset=nAgt.indexOf("Version"))!=-1)
   fullVersion = nAgt.substring(verOffset+8);
}
// In MSIE, the true version is after "MSIE" in userAgent
else if ((verOffset=nAgt.indexOf("MSIE"))!=-1) {
 browserName = "Microsoft Internet Explorer";
 fullVersion = nAgt.substring(verOffset+5);
}
// In Chrome, the true version is after "Chrome"
else if ((verOffset=nAgt.indexOf("Chrome"))!=-1) {
 browserName = "Chrome";
 fullVersion = nAgt.substring(verOffset+7);
}
// In Safari, the true version is after "Safari" or after "Version"
else if ((verOffset=nAgt.indexOf("Safari"))!=-1) {
 browserName = "Safari";
 fullVersion = nAgt.substring(verOffset+7);
 if ((verOffset=nAgt.indexOf("Version"))!=-1)
   fullVersion = nAgt.substring(verOffset+8);
}
// In Firefox, the true version is after "Firefox"
else if ((verOffset=nAgt.indexOf("Firefox"))!=-1) {
 browserName = "Firefox";
 fullVersion = nAgt.substring(verOffset+8);
}
// In most other browsers, "name/version" is at the end of userAgent
else if ( (nameOffset=nAgt.lastIndexOf(' ')+1) <
          (verOffset=nAgt.lastIndexOf('/')) )
{
 browserName = nAgt.substring(nameOffset,verOffset);
 fullVersion = nAgt.substring(verOffset+1);
 if (browserName.toLowerCase()==browserName.toUpperCase()) {
  browserName = navigator.appName;
 }
}
// trim the fullVersion string at semicolon/space if present
if ((ix=fullVersion.indexOf(";"))!=-1)
   fullVersion=fullVersion.substring(0,ix);
if ((ix=fullVersion.indexOf(" "))!=-1)
   fullVersion=fullVersion.substring(0,ix);

majorVersion = parseInt(''+fullVersion,10);
if (isNaN(majorVersion)) {
 fullVersion  = ''+parseFloat(navigator.appVersion);
 majorVersion = parseInt(navigator.appVersion,10);
}

//document.write(''
// +'Browser name  = '+browserName+'<br>'
// +'Full version  = '+fullVersion+'<br>'
// +'Major version = '+majorVersion+'<br>'
// +'navigator.appName = '+navigator.appName+'<br>'
// +'navigator.userAgent = '+navigator.userAgent+'<br>'
    //)


// Send visitor to relevant pages
if (browserName != "Chrome") {
    window.location.href = "@Url.Action("BrowserCheck", "Login")";
}

</script>

CIA/Views/Security/SessionExpired.cshtml
@{
    ViewBag.Title = "SessionExpired";
    Layout = "~/Views/Shared/_CommonLayout.cshtml";
}


<center>
    <br /><br />
    <div style="width: 40%; margin-top: 9.75%">
        <div class="Bpan grad">
            <div id="Content1" class="Bpan-body" style="line-height: 11px; margin-top: 17px;">
                <table style="width:75%">
                    <tr><td style="font-size:45px">&nbsp;</td></tr>
                    <tr>
                        <td align="center" style="text-align: center; font-family: 'Segoe UI'; padding-bottom: 20px; ">
                            <i style="font-size: 58px" class="fa fa-warning"></i>
                        </td>
                    </tr>
                    <tr>
                        <td align="center" style="text-align: center; font-family: 'Segoe UI'; padding-bottom: 20px; font-size: 12pt; ">
                            <span style="margin-top: 10px; font-family: 'Segoe UI'; font-size: 12pt;">Server session has been timed out</span>
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: center; font-family: 'Segoe UI'; font-size: 12pt; ">
                            <a id="def" href='@Url.Action("LoginView", "Security")'> Click here to Login again</a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>

    </div>
</center>


<style>
    #tbldata_wrapper {
        background: #F1F1F1;
    }

    #tbldata_processing {
        display: none;
    }

    .Bpan {
        font-size: 12pt;
        margin-bottom: 8px;
        font-family: 'Segoe UI';
        min-height: 200px;
        background-color: #ffffff;
        border: 1px solid transparent;
        border-color: #C5C5C5;
        border-radius: 0px;
        -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
        box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
    }

    .Bpan-heading {
        font-size: 12pt;
        padding: 7px 5px;
        font-family: 'Segoe UI';
        border-bottom: 1px solid transparent;
        color: #333333;
        background-color: #E1E1E1;
        border-color: #D4D4D4;
    }

    .Bpan-body {
        padding: 5px;
        font-size: 12pt;
        font-family: 'Segoe UI';
    }

    .btnSelect {
        background-color: #333;
        color: #DDDDDD;
        text-decoration: none;
    }

    .grad {
        background: red; /* For browsers that do not support gradients */
        background: -webkit-linear-gradient(left top, #ffffff, #ffffff); /* For Safari 5.1 to 6.0 */
        background: -o-linear-gradient(bottom right, #ffffff, #ffffff); /* For Opera 11.1 to 12.0 */
        background: -moz-linear-gradient(bottom right, #ffffff, #ffffff); /* For Firefox 3.6 to 15 */
        background: linear-gradient(to bottom right, #ffffff, #ffffff); /* Standard syntax */
    }
</style>